### ISSUE TITLE
unable to open file: name = 'Planck_dust_cuts_353GHz.h5'

### ISSUE THREAD

**Issue by guoyi118** [kmaylor/Map_Cutter#1]
OSError: Unable to open file (unable to open file: name = 'Planck_dust_cuts_353GHz.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Where to find the  'Planck_dust_cuts_353GHz.h5'?,

**Comment by kmaylor** [comment]
I fixed it. I had a bad version of the code pushed. 'Planck_dust_cuts_353GHz.h5' was just the name of the output file I was using. There is an option to change it.
